### ISSUE TITLE
ベンチマークかけてたらたまにapp.rbが Protocol wrong type for socket (Errno::EPROTOTYPE)

### ISSUE THREAD

**Issue by edvakf** [catatsuy/private-isu#87]
たまに出る。良いんだろうか。

```
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.227746 #61224] ERROR -- : app error: Protocol wrong type for socket (Errno::EPROTOTYPE)
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.227964 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_response.rb:54:in `write'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228092 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_response.rb:54:in `block in http_response_write'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228148 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/lint.rb:714:in `block in each'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228199 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/file.rb:110:in `block in each'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228307 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/file.rb:102:in `open'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228487 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/file.rb:102:in `each'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228590 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228747 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/lint.rb:708:in `each'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228922 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.228995 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_response.rb:54:in `http_response_write'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.229047 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:573:in `process_client'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.229096 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.229144 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.229192 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.229248 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.229295 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
03:48:08 unicorn.1 | E, [2016-03-15T03:48:08.229341 #61224] ERROR -- : /Users/atsushi/go/src/github.com/catatsuy/private-isu/webapp/ruby/vendor/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
```

**Comment by catatsuy** [comment]
自分も出るので気になっていますが、Linuxでも起こるのかは未検証です

**Comment by st-cyrill** [comment]
これ調べるの大変そう...

**Comment by catatsuy** [comment]
nginxを挟めば起こらない？
